Left user error (error)
Stopped in <exception thrown>, <unknown>
_exception :: e = _
_exception = SomeExceptionWithLocation
               (GHC.IO.Exception.IOError
                  Nothing GHC.IO.Exception.UserError [] "error" Nothing Nothing)
*** Exception: user error (error)
Stopped in <exception thrown>, <unknown>
_exception :: e = _
_exception = SomeExceptionWithLocation
               (GHC.IO.Exception.IOError
                  Nothing GHC.IO.Exception.UserError [] "error" Nothing Nothing)
Stopped in <exception thrown>, <unknown>
_exception :: e = SomeExceptionWithLocation
                    (GHC.IO.Exception.IOError Nothing GHC.IO.Exception.UserError ....)
Stopped in <exception thrown>, <unknown>
_exception :: e = _
_exception = SomeExceptionWithLocation
               (GHC.IO.Exception.IOError
                  Nothing GHC.IO.Exception.UserError [] "error" Nothing Nothing)
Left user error (error)
